version: "3.8"

services:
  app:
    build: .
    container_name: telecom_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "-m", "src"]
